# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prod CI

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: publish
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git config user.name github-actions
          git config user.email schnedo@users.noreply.github.com
          git merge main
          npm run export
          touch docs/.nojekyll
          git add -f docs
          git commit -m "publish"
          git push
